spring.application.name=LearningPlatform
# Configuración de H2 Database
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:mem:learningplatform
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driverClassName=org.h2.Driver

#Actuator configuration
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

#Info App
info.app.name="Learning Platform"
info.app.description="An online platform for learning."
info.app.version=1.0.0